# Module 1: Language Detection

**Goal:** classify the language of an incoming customer message using traditional NLP, so the
system can (a) search the right knowledge-base entries and (b) reply in the same language.

**Dataset:** [`papluca/language-identification`](https://huggingface.co/datasets/papluca/language-identification)
— 90k samples across 20 languages, pre-split into train/validation/test.

**Approach:** character n-gram TF-IDF (2–5 grams, `char_wb` analyzer) + a linear SVM
(`LinearSVC`, wrapped in `CalibratedClassifierCV` for probability estimates).

**Why char n-grams, not word n-grams?** Language identity lives at the sub-word level —
letter combinations, diacritics, accented sequences — not in shared vocabulary. Char n-grams
also work for languages without whitespace tokenization (Chinese, Japanese, Korean), where a
word-level vectorizer would be nearly useless. This is the standard, well-established approach
for language ID and needs no GPU or embeddings.

**Enhancement over the minimal ask:** a *confidence gate* — if the top prediction's
probability falls below a threshold, we don't confidently guess; we fall back to `en` and flag
`low_confidence=True`, since a wrong language guess breaks downstream knowledge-base retrieval
for the RAG module.

In [1]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))
import pandas as pd
from src import language_detection as ld

## 1.1 Load data
Tries the real HF dataset first; falls back to the small bundled CSV sample (`data/sample_language_id.csv`) if `datasets`/internet access isn't available, so this notebook always runs end to end.

In [2]:
train_df, val_df, test_df = ld.load_hf_dataset()
print(train_df.shape, val_df.shape, test_df.shape)
train_df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

(70000, 2) (10000, 2) (10000, 2)

  labels                                               text
0     pt  os chefes de defesa da estónia, letónia, lituâ...
1     bg  размерът на хоризонталната мрежа може да бъде ...
2     zh  很好，以前从不去评价，不知道浪费了多少积分，现在知道积分可以换钱，就要好好评价了，后来我就把...
3     th  สำหรับ ของเก่า ที่ จริงจัง ลอง   honeychurch  ...
4     ru                             Он увеличил давление .

## 1.2 Exploratory check
Class balance and a couple of raw examples per language.

In [3]:
print(train_df['labels'].value_counts())
train_df.sample(min(5, len(train_df)), random_state=0)

labels
pt    3500
bg    3500
zh    3500
th    3500
ru    3500
pl    3500
ur    3500
sw    3500
tr    3500
es    3500
ar    3500
it    3500
hi    3500
de    3500
el    3500
nl    3500
fr    3500
vi    3500
en    3500
ja    3500
Name: count, dtype: int64

      labels                                               text
10840     it  La polizia di Pechino ha arrestato più di 20 p...
56267     zh  我还以为会有地中海的地图，原来是个中国的。上面还标着太原郑州之类的。。。。。 这和‘远征’的...
14849     tr  Sadece km kuzeyde yaşamayı hayal bile edemem ....
62726     es  Muy bien, tal como se especifica. Mi hija la u...
47180     zh                  个人认为本书很一般，解题思路讲解得很少，更多的是提供一份参考代码。

## 1.3 Build & train the pipeline
`TfidfVectorizer(analyzer='char_wb', ngram_range=(2,5))` → `CalibratedClassifierCV(LinearSVC())`.

See `src/language_detection.py` for the full implementation (also handles the tiny-sample edge case where a class has too few examples for cross-validated calibration, falling back to an uncalibrated `LinearSVC` with a softmax-over-decision_function confidence proxy).

In [4]:
pipeline = ld.train(train_df, val_df)

              precision    recall  f1-score   support

          ar       1.00      0.99      1.00       500
          bg       1.00      1.00      1.00       500
          de       1.00      1.00      1.00       500
          el       1.00      1.00      1.00       500
          en       0.99      1.00      1.00       500
          es       1.00      1.00      1.00       500
          fr       1.00      1.00      1.00       500
          hi       1.00      0.95      0.98       500
          it       1.00      1.00      1.00       500
          ja       1.00      1.00      1.00       500
          nl       0.99      1.00      0.99       500
          pl       1.00      1.00      1.00       500
          pt       1.00      1.00      1.00       500
          ru       1.00      1.00      1.00       500
          sw       0.95      1.00      0.97       500
          th       1.00      1.00      1.00       500
          tr       0.99      1.00      1.00       500
          ur       1.00      0.97      0.98       500
          vi       1.00      1.00      1.00       500
          zh       1.00      1.00      1.00       500

    accuracy                           1.00     10000
   macro avg       1.00      1.00      1.00     10000
weighted avg       1.00      1.00      1.00     10000

## 1.4 Evaluate on held-out test set

In [5]:
ld.evaluate(pipeline, test_df)

              precision    recall  f1-score   support

          ar       1.00      1.00      1.00       500
          bg       1.00      1.00      1.00       500
          de       1.00      1.00      1.00       500
          el       1.00      1.00      1.00       500
          en       1.00      1.00      1.00       500
          es       1.00      1.00      1.00       500
          fr       1.00      1.00      1.00       500
          hi       1.00      0.97      0.98       500
          it       1.00      1.00      1.00       500
          ja       1.00      1.00      1.00       500
          nl       1.00      1.00      1.00       500
          pl       1.00      1.00      1.00       500
          pt       1.00      1.00      1.00       500
          ru       1.00      1.00      1.00       500
          sw       0.95      1.00      0.97       500
          th       1.00      1.00      1.00       500
          tr       0.99      1.00      1.00       500
          ur       1.00      0.96      0.98       500
          vi       1.00      1.00      1.00       500
          zh       1.00      1.00      1.00       500

    accuracy                           1.00     10000
   macro avg       1.00      1.00      1.00     10000
weighted avg       1.00      1.00      1.00     10000

## 1.5 Inference + confidence gating demo

In [6]:
for msg in [
    "Hello, where is my order?",
    "Hola, ¿dónde está mi pedido?",
    "Bonjour, où est ma commande?",
    "asdkj qwoe",  # gibberish -> should be low-confidence
]:
    print(msg, '->', ld.predict_language(pipeline, msg))

Hello, where is my order? -> {'language': 'en', 'confidence': 0.9831822503933073, 'low_confidence': False}
Hola, ¿dónde está mi pedido? -> {'language': 'pt', 'confidence': 0.4740801706349586, 'low_confidence': False}
Bonjour, où est ma commande? -> {'language': 'fr', 'confidence': 0.992875759685243, 'low_confidence': False}
asdkj qwoe -> {'language': 'nl', 'confidence': 0.772072090458325, 'low_confidence': False}

## 1.6 Save model for deployment

In [7]:
os.makedirs('../models', exist_ok=True)
ld.save(pipeline, '../models/language_detector.joblib')
print('Saved.')

Saved.

## Notes / decisions to defend at assessment
- Char n-grams >> word n-grams for language ID (sub-word signal, works for non-whitespace-segmented
  languages).
- `class_weight='balanced'` compensates for any label imbalance in the 20-language dataset.
- Confidence gate protects downstream retrieval from a wrong-language guess rather than always
  returning the top-1 label no matter how uncertain.
- `CalibratedClassifierCV` gives genuine probability estimates from `LinearSVC` (which has no
  native `predict_proba`), which the confidence gate depends on.